server:
  port: 9002
  tomcat:
    connection-timeout: 20000
spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.56.101:9000
        #server-addr: localhost:8848
management:
  endpoints:
    web:
      exposure:
        include: '*'
